package logger

const (
	// LevelDebug ...
	LevelDebug = "debug"
	// LevelInfo ...
	LevelInfo = "info"
	// LevelWarn ...
	LevelWarn = "warn"
	// LevelError ...
	LevelError = "error"
	// LevelPanic ...
	LevelPanic = "panic"
	// LevelFatal ...
	LevelFatal = "fatal"
)
